### ISSUE TITLE
Support Kubernetes deployment

### ISSUE THREAD

**Issue by chanwit** [mui/mui-toolpad#1495]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

As a user, I'd like to deploy Toolpad on Kubernetes.

### Examples 🌈

Here is an example of how Toolpad could be deployed on Kubernetes:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolpad
  template:
    metadata:
      labels:
        app: toolpad
    spec:
      containers:
      - name: toolpad
        image: muicom/toolpad:latest
        env:
        - name: TOOLPAD_DATABASE_URL
          value: postgresql://toolpad-app:secretpw@postgres:5432/postgres?connect_timeout=10
        - name: PORT
          value: '3000'
        - name: TOOLPAD_EXTERNAL_URL
          value: http://localhost:3000/
        ports:
        - containerPort: 3000
          name: toolpad
```

### Motivation 🔦

Kubernetes is a popular container orchestration platform that is widely used in production environments. It would be useful to have support for deploying Toolpad on Kubernetes, so that users can try it on that platform.
