### ISSUE TITLE
Allow setting url slug for pages

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1824]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Current URL of Toolpad pages looks like: https://tools-public.onrender.com/prod/pages/h71gdad

We can support having a URL slug instead of a random generated page Id.

**Comment by Janpot** [comment]
At the moment this can't be updated from the visual editor yet, but it can be set in the `page.yml`.

```yml
# toolpad/pages/myPage/page.yml
apiVersion: v1
kind: page
spec:
  id: evZC-gp # <= change this to set a custom url segment for the page. Must be unique across pages
  title: Default page
  # ...
```
