### ISSUE TITLE
Infinite loop with unstable Text Field defaultValue

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#2210]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. put a TextField on the canvas
2. bind the defaultValue prop to `String(Date.now())`
3. observe infinite loop

Page yml with reproduction:
```yml
apiVersion: v1
kind: page
spec:
  id: JxyXxRJ
  title: page1
  display: shell
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: TextField
          name: textField
          props:
            defaultValue:
              $$jsExpression: |
                String(Date.now())
```

### Current behavior 😯

The input goes in an infinite loop reinitialising the default value over and over

### Expected behavior 🤔

The default value gets initialised only once on page start
