### ISSUE TITLE
PNPM not supported; `Failed to resolve dependency`

### ISSUE THREAD

**Issue by nicu-chiciuc** [mui/mui-toolpad#2244]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Reproduction repo: https://github.com/nicu-chiciuc/repro_create-toolpad-app

Steps:
1. pnpm dlx create-toolpad-app repro_create-toolpad-app
2. cd ./repro_create-toolpad-app/
3. pnpm run dev

### Current behavior 😯

https://github.com/nicu-chiciuc/repro_create-toolpad-app

![Screenshot of error](https://raw.githubusercontent.com/nicu-chiciuc/repro_create-toolpad-app/main/screenshot.png)

### Expected behavior 🤔

I would like it to run.

### Context 🔦

I was trying to set it up in turborepo using pnpm, since pnpm is the recommended way in their docs.

I have a project that uses MUI and wanted to try it out.

### Your environment 🌎

```
dependencies:
  '@mui/toolpad':
    specifier: ^0.1.18
    version: 0.1.18(@babel/core@7.22.5)(@mui/base@5.0.0-beta.5)(react-dom@18.2.0)(react@18.2.0)(webpack@5.88.1)
```

OSX 12.5 (21G72)
