### ISSUE TITLE
the order of pages can not be saved

### ISSUE THREAD

**Issue by JerryWu1234** [mui/mui-toolpad#2655]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.  you add some pages
2. shut down the serve and reopen the serve 
3. all order will be changed 

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by Janpot** [comment]
We've been thinking about this feature before, we're not quite sure yet how we want to encode the order in the project files. So far the options that we identified:

1. an `order` property containing a `number` in the `page.yml` file.

   ```yml
   # pages/foo/page.yml
   kind: 'page'
   spec:
     order: 3 # this is the third page
   ```

   Advantages:

   - self-contained in the page file
   - human-readable

   Disadvantages

   - reordering requires writing to multiple files
   - tedious to hand edit the ordering (has to change multiple files)
   - page order is not reflected in the file system

1. an `order` property containing a [fractional index](https://www.npmjs.com/package/fractional-indexing) in the `page.yml` file.

   ```yml
   # pages/foo/page.yml
   kind: 'page'
   spec:
     order: 'gd6j' # opaque ordering
   ```

   Advantages:

   - self-contained in the page file
   - reordering requires writing to only the moved page file

   Disadvantages

   - tedious to hand edit the ordering (has to find the two adjacent pages and calculate a new index)
   - page order is not reflected in the file system

1. out of band, e.g. a meta file in the `./pages` folder containing the order

   ```yml
   # pages/meta.yml
   kind: 'pageMeta'
   spec:
     order:
       # these are names of page files
       - 'foo'
       - 'bar'
       - 'baz'
   ```

   Advantages:

   - easy to hand edit the order

   Disadvantages

   - extra file required
   - renaming/deleting becomes harder, have to maintain in multiple places
   - page order is not reflected in the file system

1. page name prefixed with sort key

   ```
   /pages
    /001-foo
      /page.yml
    /002-bar
      /page.yml
    /003-baz
      /page.yml
   ```

   Advantages:

   - page order is reflected in the file system

   Disadvantages

   - reordering requires renaming multiple files
   - tedious to hand edit the ordering (has to change multiple files)

1. any more ideas?
