### ISSUE TITLE
Toolpad should support exporting components as a URL

### ISSUE THREAD

**Issue by newguy-123** [mui/mui-toolpad#315]
Export ESM to allow embedding like Framer Handshake:
https://www.framer.com/developers/handshake/

**Comment by Janpot** [comment]
Some things to think about:
* What exactly will be exported? a page? an app? 
* How does data fetching work? 
* We're doing internal apps, what does this mean for authentication? Can you import a component of a private app?
* ...

**Comment by prakhargupta1** [comment]
From internal apps perspective, the developer might want to embed Toolpad app in their existing internal tool. I such a scenario, can they pass on auth params to grant access to Toolpad app? This is clearly more work for the developer, but they don't want other teams to log into a different platform.
So a single page should be exported. 


https://www.jotform.com/help/how-to-embed-apps-to-a-website/
https://docs.appsmith.com/advanced-concepts/embed-appsmith-into-existing-application

From external apps perspective. I think making a publicly accessible through a URL >> making it embeddable.

**Comment by buremba** [comment]
Great emphasis on the the hybrid approach and the integration with internal tools. I'm also doing proof of concept with Toolpad and it looks great so far. 

For the hybrid approach, I wonder if we can find a way to let the user switch between UI and code easily. I see that you call the YML & JSON as "output" and React & ESM as "export". Rather than treating the components created in UI as packages, we might also consider exporting to MDX from the internal JSON format and parsing MDX to the same JSON format for better readability and compatibility. MDX already supports compiling to JSX modules that can be imported in ESM. Since MDX can import modules and define `export` or Provider components, we can also compile $jsExpression easily. WDYT?

**Comment by Janpot** [comment]
> I see that you call the YML & JSON as "output" and React & ESM as "export".

I don't see the yaml/json files just as "output", they also serve as "input". They are the underlying data model that describes a toolpad application. It's hand editable but that's not the intention for day-to-day use. You can hand edit it as a power user to fulfil tasks such as bulk editing large applications, generate an application from higher level requirements,... The main requirement for it is to be declarative. We've experimented a bit and it doesn't seem likely that it's very feasable to use a non-declarative language as the data model for a Toolpad application (Also see [utopia.app](utopia.app) or [blocksUI](https://blocks-ui.com/))

We see "export" or "eject" as a one-way action only, producing runnable code where the focus would be on one of the following use cases:
- Exported code could be more performant than the Toolpad runtime, you'd use it to create runnable artifacts to run applications in production. Exporting in CI every time you deploy and e.g. packaging it up as a docker container, or directly importing in an existing React application
- You outgrow the capabilities of Toolpad and wish to continue the pro-code way. You don't want to start from scratch and eject the application as a starting point to continue the pro-code way. This is an advanced case of the previous point where an extra constraint is that the output must be human readable and clean code.

**Comment by buremba** [comment]
Thanks for the answer Jan! I agree that most tools separate the "exporting" feature in a way that you can't go back to the visual editor but I'm trying to highlight that it doesn't necessarily need to be that way. 

Both utopia.app and blocksUI generate React components with JSX, which is very flexible in a way a visual editor can't easily be used on top. This is because you might have variables, inline functions, outer loops, etc.

Let's go over the following page:

```yml
apiVersion: v1
kind: page
spec:
  id: od4ulyy
  title: dashboard
  display: shell
  content:
    - component: Text
      name: markdown
      props:
        mode: text
        value:
          $$jsExpression: |
            mydata
        variant: h1
        loading: false
    - component: PageRow
      name: pageRow
      props:
        justifyContent: start
      children:
        - component: Chart
          name: chart
          layout:
            columnSize: 1.3388946819603753
          props:
            data:
              - label: dataSeries1
                kind: line
                data:
                  $$jsExpression: |
                    [{ count: 10 }]
            sx:
              bgcolor: background.paper
        - component: Chart
          name: chart1
          props:
            data:
              - label: dataSeries1
                kind: line
                data: []
          layout:
            columnSize: 0.6611053180396247
 queries:
    - name: mydata
      query:
        function: dasdas.ts#default
        kind: local
      parameters:
        - name: message
          value: test
```

It can be converted to MDX as follows:

```md
import dasdas from 'dasdas'

export const mydata = dasdas('test');

<Text id="markdown"  mode="text" value="{mydata}" variant="h1" loading=false>
<PageRow justifyContent="start"/>
  <Layout columnSize=1.3388946819603753>
      <Chart id="chart1" data={ [{ count: 10 }] kind={'line'} sx={{bgcolor: 'background.paper'}}/>
  </Layout>
  <Layout columnSize=0.6611053180396247>
      <Chart id="chart2" kind={'line'}  data=[] data={query.data}/>
  </Layout>
</PageRow>
```

The MDX above is completely valid and I believe covers what's represented in the YML. We can restrict the export syntax anywhere but on top of the file similar to imports to simplify parsing and avoid edge cases. If there is problems with export syntax, the data can even be defined in frontmatter as well.

The cool part of that since the above is a valid MDX, it's portable similar to React-generated code that can be used outside of Toolpad. Toolpad's custom data providers/components are flexible enough that I might not need to take my "exported" code and continue the development outside of Toolpad so MDX is kinda the output layer here, which is much more readable compared to YML and JSON, which are much harder to read. I can easily read this MDX and understand the layout unline the YML counterpart. I might be missing important details though, WDYT?
